package com.hrms.services;

import com.hrms.core.models.Employee;
import com.hrms.core.models.RecruitmentRequest;
import com.hrms.core.models.Team;
import com.hrms.core.models.UsersRole;
import com.hrms.core.repositories.EmployeeRepository;
import com.hrms.core.repositories.RecruitmentRequestRepository;
import com.hrms.core.repositories.RoleRepository;
import com.hrms.core.repositories.TeamRepository;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Optional;

@Service
public class RecruitmentRequestService {

    private final RecruitmentRequestRepository recruitmentRequestRepository;
    private final EmployeeRepository employeeRepository;
    private final RoleRepository roleRepository;
    private final TeamRepository teamRepository;
    private final PasswordEncoder passwordEncoder;
    private final InboxService inboxService;

    public RecruitmentRequestService(RecruitmentRequestRepository recruitmentRequestRepository,
                                   EmployeeRepository employeeRepository,
                                   RoleRepository roleRepository,
                                   TeamRepository teamRepository,
                                   PasswordEncoder passwordEncoder,
                                   InboxService inboxService) {
        this.recruitmentRequestRepository = recruitmentRequestRepository;
        this.employeeRepository = employeeRepository;
        this.roleRepository = roleRepository;
        this.teamRepository = teamRepository;
        this.passwordEncoder = passwordEncoder;
        this.inboxService = inboxService;
    }

    /**
     * Returns the next available auto-generated employee ID.
     * Returns null if no auto-generated IDs have been set yet, meaning
     * the HR manager needs to provide a starting number on the first request.
     */
    public Long generateNextEmployeeId() {
        Long maxAutoId = recruitmentRequestRepository.findMaxAutoGeneratedEmployeeId();
        if (maxAutoId == null) {
            return null; // No starting number set yet — HR must provide one
        }
        return maxAutoId + 1;
    }

    /**
     * Submit a new recruitment request (Stage 1)
     */
    @Transactional
    public RecruitmentRequest submitRequest(RecruitmentRequest request) {
        // Check for duplicate national ID in active requests
        if (recruitmentRequestRepository.existsActiveByNationalId(request.getNationalId())) {
            throw new IllegalArgumentException("An active request or employee with this national ID already exists");
        }
        
        // Check for duplicate email
        if (employeeRepository.findByEmail(request.getEmail()).isPresent()) {
            throw new IllegalArgumentException("An employee with this email already exists");
        }

        request.setStatus(RecruitmentRequest.STATUS_PENDING_MANAGER);
        request.setRequestedAt(LocalDateTime.now());
        RecruitmentRequest saved;
        try {
            saved = recruitmentRequestRepository.save(request);
        } catch (DataIntegrityViolationException e) {
            throw new IllegalArgumentException("رقم الهوية هذا موجود بالفعل في النظام. لا يمكن إنشاء طلب مكرر.");
        }

        // Notify HR role about new recruitment request
        inboxService.sendMessage(
            "New Recruitment Request",
            "A new recruitment request for " + saved.getJobDescription() + " has been submitted and is pending review.",
            "HR",
            "System",
            "MEDIUM"
        );

        return saved;
    }

    /**
     * Process a recruitment request (Stage 2 & 3)
     */
    @Transactional
    public RecruitmentRequest processRequest(Long requestId, String action, String note, BigDecimal adjustedSalary, Long processorId, String processorRole) {
        Optional<RecruitmentRequest> optional = recruitmentRequestRepository.findById(requestId);
        if (optional.isEmpty()) {
            throw new IllegalArgumentException("Recruitment request not found");
        }

        RecruitmentRequest request = optional.get();
        String currentStatus = request.getStatus();

        if (RecruitmentRequest.STATUS_APPROVED.equals(currentStatus) || RecruitmentRequest.STATUS_REJECTED.equals(currentStatus)) {
            throw new IllegalStateException("Request has already been finalized");
        }

        if ("Rejected".equalsIgnoreCase(action)) {
            request.setStatus(RecruitmentRequest.STATUS_REJECTED);
            request.setManagerNote(note);
            request.setProcessedAt(LocalDateTime.now());
            request.setApprovedBy(processorId);
            
            RecruitmentRequest saved = recruitmentRequestRepository.save(request);
            
            // Notify the original requester about rejection
            if (saved.getRequestedBy() != null) {
                inboxService.sendPersonalMessage(
                    "Recruitment Request Rejected",
                    "Your recruitment request for " + saved.getJobDescription() + " has been rejected.",
                    saved.getRequestedBy(),
                    "System",
                    "HIGH"
                );
            }
            
            return saved;
        }

        // Action is "Approved"
        String oldStatus = request.getStatus();
        if (RecruitmentRequest.STATUS_PENDING_MANAGER.equals(currentStatus)) {
            // Manager Approval -> Move to Payroll
            request.setStatus(RecruitmentRequest.STATUS_PENDING_PAYROLL);
            if (adjustedSalary != null) {
                request.setExpectedSalary(adjustedSalary);
            }
        } else if (RecruitmentRequest.STATUS_PENDING_PAYROLL.equals(currentStatus)) {
            // Payroll Approval -> Move to Final Approved and Create Employee
            request.setStatus(RecruitmentRequest.STATUS_APPROVED);
            if (adjustedSalary != null) {
                request.setExpectedSalary(adjustedSalary);
            }
            createEmployeeFromRequest(request);
        }

        request.setManagerNote(note);
        request.setProcessedAt(LocalDateTime.now());
        request.setApprovedBy(processorId);

        RecruitmentRequest saved = recruitmentRequestRepository.save(request);
        
        // Notify the original requester about status change
        if (saved.getRequestedBy() != null && !saved.getStatus().equals(oldStatus)) {
            inboxService.sendPersonalMessage(
                "Recruitment Request Updated",
                "Your recruitment request for " + saved.getJobDescription() + " is now " + saved.getStatus().replace("_", " ") + ".",
                saved.getRequestedBy(),
                "System",
                "MEDIUM"
            );
        }

        return saved;
    }

    private void createEmployeeFromRequest(RecruitmentRequest request) {
        // Find default role and team based on department
        Long roleId = roleRepository.findByRoleName("EMPLOYEE")
                .map(UsersRole::getRoleId).orElse(null);

        Long teamId = teamRepository.findAll().stream()
                .filter(t -> t.getName().equalsIgnoreCase(request.getDepartment()))
                .map(Team::getTeamId)
                .findFirst().orElse(null);

        // Determine the employee ID to use
        Long employeeId = request.getEmployeeId();

        if (Boolean.TRUE.equals(request.getAutoGenerateEmployeeId())) {
            if (employeeId == null) {
                // Auto-generate: find max previous auto-generated ID + 1
                Long maxAutoId = recruitmentRequestRepository.findMaxAutoGeneratedEmployeeId();
                if (maxAutoId == null) {
                    throw new IllegalStateException(
                        "No starting employee ID has been set yet. " +
                        "Please provide a starting number on the first recruitment request."
                    );
                }
                employeeId = maxAutoId + 1;
            }
            // If employeeId is provided, use it as the starting number (first time or reset)
        }

        // Create new employee record
        Employee.EmployeeBuilder builder = Employee.builder()
                .fullName(request.getFullName())
                .email(request.getEmail())
                .passwordHash(passwordEncoder.encode("Welcome@123"))
                .roleId(roleId)
                .teamId(teamId)
                .baseSalary(request.getExpectedSalary())
                .status("Active");

        if (employeeId != null) {
            builder.employeeId(employeeId);
        }

        Employee employee = builder.build();
        employeeRepository.save(employee);
    }

    /**
     * Get pending requests for the current user based on their role
     */
    public Page<RecruitmentRequest> getPendingRequestsForRole(String roleName, String department, Pageable pageable) {
        if ("MANAGER".equals(roleName)) {
            // Managers see ALL requests pending manager review (not filtered by department)
            return recruitmentRequestRepository.findByStatus(RecruitmentRequest.STATUS_PENDING_MANAGER, pageable);
        } else if ("PAYROLL".equals(roleName)) {
            // Payroll sees all requests pending payroll review
            return recruitmentRequestRepository.findByStatus(RecruitmentRequest.STATUS_PENDING_PAYROLL, pageable);
        } else if ("HR".equals(roleName) || "ADMIN".equals(roleName) || "SUPER_ADMIN".equals(roleName)) {
            // HR/Admin see everything pending
            return recruitmentRequestRepository.findAllByStatuses(Arrays.asList(
                    RecruitmentRequest.STATUS_PENDING_MANAGER,
                    RecruitmentRequest.STATUS_PENDING_PAYROLL
            ), pageable);
        }
        return Page.empty();
    }

    public Page<RecruitmentRequest> getPendingRequests(Pageable pageable) {
        return recruitmentRequestRepository.findAllByStatuses(Arrays.asList(
                RecruitmentRequest.STATUS_PENDING_MANAGER,
                RecruitmentRequest.STATUS_PENDING_PAYROLL
        ), pageable);
    }

    public Page<RecruitmentRequest> getPendingRequestsByDepartment(String department, Pageable pageable) {
        return recruitmentRequestRepository.findByDepartmentAndStatuses(department, Arrays.asList(
                RecruitmentRequest.STATUS_PENDING_MANAGER,
                RecruitmentRequest.STATUS_PENDING_PAYROLL
        ), pageable);
    }

    public Page<RecruitmentRequest> getUserRequests(Long userId, Pageable pageable) {
        return recruitmentRequestRepository.findByRequestedBy(userId, pageable);
    }

    public Page<RecruitmentRequest> getRequestsByStatus(String status, Pageable pageable) {
        return recruitmentRequestRepository.findByStatus(status, pageable);
    }

    /**
     * Get all recruitment requests regardless of status
     */
    public Page<RecruitmentRequest> getAllRequests(Pageable pageable) {
        return recruitmentRequestRepository.findAllRequests(pageable);
    }

    public Optional<RecruitmentRequest> getRequestById(Long requestId) {
        return recruitmentRequestRepository.findById(requestId);
    }
}
