package com.hrms.core.repositories;

import com.hrms.core.models.RecruitmentRequest;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface RecruitmentRequestRepository extends JpaRepository<RecruitmentRequest, Long> {

    /**
     * Find all pending recruitment requests by multiple statuses
     */
    @Query("SELECT r FROM RecruitmentRequest r WHERE r.status IN :statuses ORDER BY r.requestedAt DESC")
    Page<RecruitmentRequest> findAllByStatuses(@Param("statuses") List<String> statuses, Pageable pageable);

    /**
     * Find all requests created by a specific HR user
     */
    @Query("SELECT r FROM RecruitmentRequest r WHERE r.requestedBy = :requestedBy ORDER BY r.requestedAt DESC")
    Page<RecruitmentRequest> findByRequestedBy(@Param("requestedBy") Long requestedBy, Pageable pageable);

    /**
     * Find all recruitment requests regardless of status
     */
    @Query("SELECT r FROM RecruitmentRequest r ORDER BY r.requestedAt DESC")
    Page<RecruitmentRequest> findAllRequests(Pageable pageable);

    /**
     * Find all requests with a specific status
     */
    @Query("SELECT r FROM RecruitmentRequest r WHERE r.status = :status ORDER BY r.requestedAt DESC")
    Page<RecruitmentRequest> findByStatus(@Param("status") String status, Pageable pageable);

    /**
     * Find requests by department and status
     */
    @Query("SELECT r FROM RecruitmentRequest r WHERE r.department = :department AND r.status IN :statuses ORDER BY r.requestedAt DESC")
    Page<RecruitmentRequest> findByDepartmentAndStatuses(@Param("department") String department, @Param("statuses") List<String> statuses, Pageable pageable);

    /**
     * Check if a national ID already exists in non-rejected requests
     */
    @Query("SELECT COUNT(r) > 0 FROM RecruitmentRequest r WHERE r.nationalId = :nationalId AND r.status != 'REJECTED'")
    boolean existsActiveByNationalId(@Param("nationalId") String nationalId);

    /**
     * Find the maximum employee ID from approved recruitment requests that used auto-generation.
     * Returns null if no auto-generated IDs exist yet.
     */
    @Query("SELECT MAX(r.employeeId) FROM RecruitmentRequest r WHERE r.autoGenerateEmployeeId = true AND r.status = 'APPROVED'")
    Long findMaxAutoGeneratedEmployeeId();
}
